name: m2ai-ac
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - expat=2.7.3
  - icu=73.2
  - intel-openmp=2025.0.0
  - ld_impl_linux-64=2.44
  - libblas=3.11.0
  - libcblas=3.11.0
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgomp=15.2.0
  - libhwloc=2.12.1
  - liblapack=3.11.0
  - libnsl=2.0.0
  - libopenblas=0.3.30
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - llvm-openmp=20.1.8
  - mkl=2025.2.0
  - ncurses=6.5
  - numpy=2.2.6
  - openssl=3.6.0
  - pip=25.3
  - pthread-stubs=0.3
  - python=3.10.19
  - python_abi=3.10
  - readline=8.3
  - scipy=1.15.2
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tbb=2022.3.0
  - tk=8.6.15
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - annotated-types==0.7.0
      - audioread==3.1.0
      - blis==1.3.3
      - catalogue==2.0.10
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - cloudpathlib==0.23.0
      - confection==0.1.5
      - contourpy==1.3.2
      - cycler==0.12.1
      - cymem==2.0.13
      - decorator==5.2.1
      - editdistpy==0.1.6
      - en-core-web-sm==3.8.0
      - filelock==3.20.2
      - fonttools==4.61.1
      - fsspec==2025.12.0
      - hf-xet==1.2.0
      - huggingface-hub==0.36.0
      - hyperpyyaml==1.2.3
      - idna==3.11
      - jinja2==3.1.6
      - joblib==1.5.3
      - kiwisolver==1.4.9
      - language-tool-python==3.2.2
      - lazy-loader==0.4
      - librosa==0.11.0
      - llvmlite==0.46.0
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - mdurl==0.1.2
      - mpmath==1.3.0
      - msgpack==1.1.2
      - murmurhash==1.0.15
      - networkx==3.4.2
      - nltk==3.9.2
      - numba==0.63.1
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - packaging==25.0
      - pandas==2.3.3
      - pillow==12.1.0
      - platformdirs==4.5.1
      - pooch==1.8.2
      - preshed==3.0.12
      - psutil==7.2.1
      - pycparser==2.23
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pygments==2.19.2
      - pyparsing==3.3.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - rapidfuzz==3.14.3
      - regex==2025.11.3
      - requests==2.32.5
      - rich==14.2.0
      - ruamel-yaml==0.18.17
      - ruamel-yaml-clib==0.2.15
      - safetensors==0.7.0
      - scikit-learn==1.7.2
      - sentence-transformers==5.2.0
      - sentencepiece==0.2.1
      - six==1.17.0
      - smart-open==7.5.0
      - sounddevice==0.5.3
      - soundfile==0.13.1
      - soxr==1.0.0
      - spacy==3.8.11
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - speechbrain==1.0.3
      - srsly==2.5.2
      - srt==3.5.3
      - sympy==1.14.0
      - symspellpy==6.9.0
      - tabulate==0.9.0
      - textblob==0.19.0
      - thinc==8.3.10
      - threadpoolctl==3.6.0
      - tokenizers==0.22.1
      - toml==0.10.2
      - torch==2.9.1
      - torchaudio==2.9.1
      - tqdm==4.67.1
      - transformers==4.57.3
      - triton==3.5.1
      - typer-slim==0.21.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - urllib3==2.6.2
      - vadersentiment==3.3.2
      - vosk==0.3.45
      - wasabi==1.1.3
      - weasel==0.4.3
      - websockets==15.0.1
      - wrapt==2.0.1
prefix: /home/neves/miniconda3/envs/m2ai-ac
